<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_FailSearch</name>
   <tag></tag>
   <elementGuidId>e92dcea2-1164-4d20-9069-0393e69c1da8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[.='No Records Found']</value>
   </webElementProperties>
</WebElementEntity>
