<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ReportToError</name>
   <tag></tag>
   <elementGuidId>4e2f253a-c825-4666-ae84-2fe7ab61f486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[@id='frmAddReportTo']//li[2]//span[@class='validation-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@id='frmAddReportTo']//li[2]//span[@class='validation-error']</value>
   </webElementProperties>
</WebElementEntity>
