<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Success</name>
   <tag></tag>
   <elementGuidId>a3291993-4d15-46f4-a28a-da0c86a4d811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.message</value>
   </webElementProperties>
</WebElementEntity>
