<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ttl_EmployeeInformation</name>
   <tag></tag>
   <elementGuidId>e3926f59-ff26-477c-ba08-93aa4c61d0ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.toggle</value>
   </webElementProperties>
</WebElementEntity>
