<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>null</name>
   <tag></tag>
   <elementGuidId>46313388-aa89-47cc-8fc4-e3da7c7207b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[@id='frmEmpJobDetails']//ol[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@id='frmEmpJobDetails']//ol[1]</value>
   </webElementProperties>
</WebElementEntity>
