<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opt_SUFinance</name>
   <tag></tag>
   <elementGuidId>b2c5363e-294e-45cc-92e3-7f1a10431348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[.='Finance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//option[.='Finance']</value>
   </webElementProperties>
</WebElementEntity>
