<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CancelDelete</name>
   <tag></tag>
   <elementGuidId>e01deefd-1e95-4a6f-a1b0-4f52b0953ec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.cancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.cancel</value>
   </webElementProperties>
</WebElementEntity>
