<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_LogOut</name>
   <tag></tag>
   <elementGuidId>403c8bf3-1e20-4c58-9e8d-0bdef486de3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>a[href='/index.php/auth/logout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[.='Logout']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>a[href='/index.php/auth/logout']</value>
   </webElementProperties>
</WebElementEntity>
