<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>null</name>
   <tag></tag>
   <elementGuidId>a4855a09-8f6b-4a3b-abb6-1355fb8a6116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ol[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ol[3]</value>
   </webElementProperties>
</WebElementEntity>
